### ISSUE TITLE
Provide parthenon::prelude, perhaps with subsets

### ISSUE THREAD

**Issue by jdolence** [lanl/parthenon#100]
The way Rust solves this is they have a "prelude" module for common names. So we could perhaps have something like:

```c++
namespace parthenon { namespace prelude {
// Re-exports
using Real = ::parthenon::Real;
using MeshBlock = ::parthenon::MeshBlock;
using ParArrayND = ::parthenon::PayArrayND;
} }
```

And then in the user code, you could write:
```c++
using namespace parthenon::prelude;
```

You should be careful, though, to keep that `prelude` namespace fairly lean - only things that are used by essentially ever single user. You could potentially split the preludes into something like `parthenon::task::prelude` and `parthenon::app::prelude` to distinguish being names commonly used by apps and names commonly used by task implementations.

_Originally posted by @AndrewGaspar in https://github.com/lanl/parthenon/pull/75_

**Comment by Yurlungur** [comment]
Forwarding my comment from @AndrewGaspar's MR #110.

> I understand the utility of this, but it does make it a little hard to track down where a given name is coming from. I know you can chase through the headers, but is there a way to document this a little more verbosely? Maybe we could keep a master doc of what names are provided by each prelude namespace?

Thoughts?

**Comment by jdolence** [comment]
It's not totally clear to me what you're asking for.  I *think* it's a documented list of what a given header includes and what a given namespace provides, so that you can refer to it to know what's been exposed.  Thing is, I'm not sure what clearer expression of that there is than the header you're including (that is basically just a listing of the headers and using statements it's importing).  I'd argue the header is self-documenting and has the added advantage that things are defined in just one place.

**Comment by Yurlungur** [comment]
I want one document, as opposed to multiple header files, to save me the effort of chasing through multiple header files to see what's been imported. I'm thinking just a markdown file would do fine. We could even have this be auto-generated by the build system or the CI: just have it read the prelude headers and combine them into one big file for easy reference.

**Comment by jdolence** [comment]
OK, sure.  An auto-generated markdown file would be fine.  Otherwise, I worry it would end up prone to inconsistency and cause more harm than good.  I'd suggest this not hold up #110, though.

**Comment by Yurlungur** [comment]
I'm fine with merging in now.
