### ISSUE TITLE
Exclusive par_for

### ISSUE THREAD

**Issue by forrestglines** [lanl/parthenon#104]
Just a quality of life change - should we introduce a `par_for` with exclusive end index? Name it `par_efor` or something like that? In most of the AMR and physics kernels the current inclusive `par_for` makes sense, but occasionally when we're dealing with raw arrays an exclusive `for` would be more convenient.

**Comment by AndrewGaspar** [comment]
In general I prefer inclusive lower bound, exclusive upper bound because that's how most C loops are written. Actually, I hadn't realized that wasn't the default for par_for already. :P

**Comment by Yurlungur** [comment]
I think this is a good idea. The reason it's inclusive upper bound is because we inherited that convention from `Athena++`. That's not a bad thing, inclusive and exclusive are just conventions after all. But I don't see a reason not to include an explicitly exclusive one.

**Comment by AndrewGaspar** [comment]
I'd say, let's close this, and if somebody has occasion to add an exclusive par_for, then we can do so?
