### ISSUE TITLE
Examples don't work with MPI

### ISSUE THREAD

**Issue by jlippuner** [lanl/parthenon#107]
Looking into this

**Comment by jdolence** [comment]
huh, they've been working for me.  this is master?

**Comment by jlippuner** [comment]
Yes, on master. They work for me if I compile without MPI, but with MPI they just hang. Maybe it's an issue with my local MPI, but I thought that it used to work with MPI on my system.

**Comment by jlippuner** [comment]
Ok, I think it's an issue with my system. Will close this once I've figured it out

**Comment by jlippuner** [comment]
Alright, I fixed my MPI and the examples all work now. Sorry for the false alarm.
