### ISSUE TITLE
Input file format and parser

### ISSUE THREAD

**Issue by jlippuner** [lanl/parthenon#109]
Do we want to keep and maintain our own input file format and associated parser? I feel we shouldn't reinvent the wheel and go with some well-known, widely used structured file format, like YAML or JSON. Any thoughts?

What are the must-have and would-be-nice-to-have features of the input file?

**Comment by Yurlungur** [comment]
I think our input files are a lot more readable than a JSON or YAML file. Our files are basically already a funnily formatted subset of YAML. But the funny formatting buys you a lot. It reduces visual noise and makes the files easier to read. @jmstone may also have some insight into why the input parser was designed the way it was.

One comment if we go a YAML or JSON route. We need to be careful to pick a parser that actually compiles with our compiler stack. I recently used [this library](https://github.com/nlohmann/json) for a JSON parser for a different project. It works wonderfully except that `nvcc` can't compile it. We are likely to run into problems like that with any library that uses modern `C++`. The developers of these libraries are probably not thinking about accelerator code.

**Comment by jdolence** [comment]
I'd second sticking with what we've got.  I rather like the simplicity/readability of the current input files and the parser code really isn't too bad (I just spent some time in there to enable multiline parameter lists).

**Comment by jlippuner** [comment]
I think YAML would have exactly the same number of lines as the current input file format. The number of characters would be almost identical. JSON would indeed be more verbose, though.

**Comment by Yurlungur** [comment]
@jlippuner do you have a preferred C++ YAML parser? How significant of a dependency would it be to add?

**Comment by jmstone** [comment]
Thanks for mentioning me on this issue, Jonah, so I could comment.  I have strong opinions about this topic.  I would *very* much like to keep the current input file format.  It dates back to ~2002 when we were writing Athena.  We specifically looked at YAML, XML, and other formats and decided our own design was cleaner, easier to use, and provided all the functionality we needed.  Peter Teuben then implemented the parser (ParameterInput).  There are now literally thousands of input files based on this design used for hundreds of projects, and having to move to another format would be an incredible pain.  Plus, I hate adding new dependencies unless absolutely necessary.  They will ALWAYS bite you sometime in the future.  My two cents.

**Comment by JoshuaSBrown** [comment]
@jmstone makes some very good points, if we are going to add support for a different file parser, it might make sense to add it as an addition as opposed to a replacement. I feel that there is definitely an argument for allowing the input file to be parsed using an existing format such as .yaml or json. Particularly when post processing the data, if there is a need to read in the input file, importing file parsers for widely supported file formats becomes trivial whereas using the current input format would require writing a parser from scratch. Outside of using parthenon how large of a need is there to parse the input files?

**Comment by jmstone** [comment]
In the almost 20y we've been using this format, we've never had a need to parse the input files for post-processing.  Even if you do, our format is so simple it is easy to adopt the reader in any post-processing script.  So using externally-supported formats to make post-processing easier has never been a problem.  All of the information needed for post-processing is embedded in the *output* formats themselves, e.g. VTK, HDF5, etc.  The only exception are the restart files, which contain a copy of the input deck.  However, the restart files have to be a custom format anyways, so again this has never been a problem.

**Comment by Yurlungur** [comment]
> All of the information needed for post-processing is embedded in the output formats themselves

This is definitely something we should preserve going forward, by the way. I think it's pretty important to marry simulation parameters to the output data. If they online live in the input file... well, input files get edited and lost. It's easier to keep track of things if it's all tied together.

**Comment by jdolence** [comment]
:thumbsup::thumbsup:, one for the each of ya

**Comment by jlippuner** [comment]
Alright, it sounds like we want to keep the input file and parser as they are. Thanks for the feedback.
