### ISSUE TITLE
Documenting common builds

### ISSUE THREAD

**Issue by Yurlungur** [lanl/parthenon#111]
The conversation on MR #96 got me thinking that we should really document the recipes for building our code on common machines. I'm thinking another markdown file in `docs` would do nicely. As we get `parthenon` running on more and more systems, the slightly different incantation per machine will become increasingly hard to remember. I would suggest we start with the power9 nodes on `Darwin` that @jlippuner just got working.

**Comment by jlippuner** [comment]
Great idea! But I want to point out that @AndrewGaspar got it working on Darwin's Power 9 nodes. I just found that we need at least CMake 3.15.

**Comment by Yurlungur** [comment]
Oops yes. Sorry, @AndrewGaspar! Mis-attributed there.

**Comment by AndrewGaspar** [comment]
I'm of two minds on this - I wish that building was more streamlined for common systems. And I have no opposition to even hard-coding specializations for specific platforms as long as they're correctly scoped.

But, I don't really love having a bunch of LANL specific stuff in the code, partly because it's obscure and not testable by our non-LANL compatriots, and also because it may lead to LANL developers failing to keep the code building outside those environments. EAP actually has this problem where it's difficult to build on arbitrary platforms (though part of that is just because it's big).

I don't know, I don't think my concerns are actually that strong, it's more small things. I might just submit a PR that detects Darwin+XL (and we could add additional customizations if necessary). That would be even better than a doc because it would be in the code.

**Comment by Yurlungur** [comment]
I'd rather avoid having LANL-specific stuff in the code. In my experience, hard-coded, system-specific pieces of a build system rot quickly when a machine falls out of use. I am also nervous about putting machine-specific things into `CMake` since that could become hard to maintain.

That's why I advocated documentation. Of course, I'm open to better solutions. Some large projects I've worked with in the past have had system-specific configuration automated via python scripts which auto-detect what machine you're on and then read in what to do from a database of machine-specific configuration files. See, .e.g, [nubhlight](https://github.com/lanl/nubhlight/) or [simfactory](http://simfactory.org/). I don't know how easy it is to integrate something like that into `cmake`.

**Comment by AndrewGaspar** [comment]
Take a look at #114 and tell me what you think.

**Comment by pgrete** [comment]
I'm also in favor of documenting builds.
We did sth similar for K-Athena as there are some subtle different between different machine even if they use the same architecture, see https://gitlab.com/pgrete/kathena/-/wikis/Building%20and%20running%20k%20athena

If it comes to documenting versus providing build file I vote for the former mainly for the reason to have an "easy to parse" overview on how to build on different system (as this may ease debugging/fixing/adapting in case of builds fail and don't invoke the expectation that it'll always work as expected -- as you said, machines and environments change).
(When I first started working with Kokkos, CMake, etc. my main goto for build issues were the build docs of other code that used similar interfaces, which was to me a lot easier than trying to understand cmake to fix sth.)

**Comment by Yurlungur** [comment]
> Take a look at #114 and tell me what you think.

This is a really cool approach, @AndrewGaspar thanks for putting it together!  I'd definitely like to integrate that in.

Perhaps we should do both---include specialized code to automate when appropriate and document when to invoke what. One thing @AndrewGaspar's `cmake` approach doesn't do is, for example, tell us what modules to load, etc., which is worth documenting I think.

**Comment by jlippuner** [comment]
I agree that we should document how to build on common systems. What modules to load, what to watch out for, etc.
 
Have w reached a consensus on where this documentation should live? In `parthenon/docs`? On the Github wiki? Or are we worried about putting information (e.g. what modules are available) about LANL internal systems out in the open?

**Comment by pgrete** [comment]
I'm happy with both options and vote for starting this sooner than later.

**Comment by Yurlungur** [comment]
Since we've made the habit of putting code documentation in the codebase, I think builds belong there too. I've created a MR. #138. Please take a look. Let's make a habit of adding our build instructions there as we work.

**Comment by Yurlungur** [comment]
Resolved by #138
