### ISSUE TITLE
Getting CI for Power9 Somehow?

### ISSUE THREAD

**Issue by Yurlungur** [lanl/parthenon#112]
Issue #96 got me thinking that it would be nice to have CI for power9 builds as well as intel and cuda builds. It seems there are a couple of paths to getting this:

1. Use @pgrete's gitlab to integrate to a power9 machine.
2. Use the gitlab instance on Darwin.

Both paths seem to have issues. I figured I'd start a thread here to discuss paths forward. Tagging @junghans @gshipman @JoshuaSBrown and @pgrete as people who may have some insight.

**Comment by junghans** [comment]
Triggering darwin is not a good idea due to security concerns from external PRs @ktsai7 can go more in detail.

**Comment by JoshuaSBrown** [comment]
I'm wondering what problems would be involved if we submitted pull request via a private mirror on gitlab...

**Comment by ktsai7** [comment]
There are various issues we could get into, but the fact that if an external source can trigger CI, or submit a job, on our internal resources, raises a lot of security questions such as... 
Since we have data that's not open, are all the external source/server maintainers US person? or at least approved like our maintainers internally?
Also, maintainers can grant access to the registered runners on that server to other projects without going through us, so this is definitely not going to go down well with the security teams.

With standalone node like shell or docker runners, we are not connect to the regular Darwin resources, but we already have issues mentioned above and more.
Batch runners are not only going to have the same issues, but being connect to our entire Darwin resources only makes it even worse.

**Comment by pgrete** [comment]
Other labs have running Gitlab instances with expansive CI capabilities - also thinking around the ECP here.
Is there any chance we could link to those?

**Comment by AndrewGaspar** [comment]
Could we potentially set it up to somehow run CI on Darwin only on master? That way it was reviewed and approved by one of us before it got merged. It won't stop people from breaking our Power9 builds, but we'd at least catch when the issues are introduced.

**Comment by JoshuaSBrown** [comment]
> I'm wondering what problems would be involved if we submitted pull requests via a private mirror on gitlab... but then I don't think gitlab has a version of a runner.

Correction: I just realized I had this backwards, gitlab has runners, github does not.

**Comment by JoshuaSBrown** [comment]
I'm wondering if it is possible to only trigger gitlab ci on darwin for a known user group. That way by default the ci would not be triggered, unless the user was appropriately vetted.

**Comment by JoshuaSBrown** [comment]
> Could we potentially set it up to somehow run CI on Darwin only on master? That way it was reviewed and approved by one of us before it got merged. It won't stop people from breaking our Power9 builds, but we'd at least catch when the issues are introduced.

I think you might be able to do this with protected branches.

**Comment by ktsai7** [comment]
> Could we potentially set it up to somehow run CI on Darwin only on master? That way it was reviewed and approved by one of us before it got merged. It won't stop people from breaking our Power9 builds, but we'd at least catch when the issues are introduced.

I am not sure if this is even still related to the issue we started with, but couldn't you just add the `only` keyword in the gitlab-ci script so the ci pipelines would only get triggered for master?

**Comment by Yurlungur** [comment]
> > Could we potentially set it up to somehow run CI on Darwin only on master? That way it was reviewed and approved by one of us before it got merged. It won't stop people from breaking our Power9 builds, but we'd at least catch when the issues are introduced.
> 
> I am not sure if this is even still related to the issue we started with, but couldn't you just add the `only` keyword in the gitlab-ci script so the ci pipelines would only get triggered for master?

@AndrewGaspar, please correct me if I'm wrong. I think the question is whether or not doing so would be acceptably secure. We have CI running (which we'd like to continue to run) on @pgrete's gitlab per commit. But I think @AndrewGaspar is suggesting we run power9 builds on master on Darwin on a schedule or something. That way we have some testing on architectures of interest and the code that gets run has been vetted by us at least once.

**Comment by davidorville** [comment]
I manage the Darwin ASC research testbed at LANL. Darwin sits on LANL's internal, unclassified restricted network (the Yellow Network). I'm curious to know what "labs have running Gitlab instances with expansive CI capabilities" on their restricted networks? The ECP federated solution is still a work in progress and I've been collaborating with the LANL team to test capabilities as they become available. So far, we've just got the SLURM batch runner capability  available for internal Darwin users. Access to internal resources within a Lab's restricted network is an issue for any Lab. If one of the NNSA Labs has solved this CI access issue in an approved way, send me their contact info and I'll reach out. If there is prior art, I can use that to discuss a possible LANL solution with the CIO.

**Comment by davidorville** [comment]
One possible path forward is to make sure anyone who would generate a commit that triggers CI has a corresponding LANL account on the Yellow Network (and an approved account on Darwin as well). There is the whole issue of mapping github users to LANL users but ECP has a mechansim that might work for that (assuming CIO buy-in). The main issue with this is that if everyone on github has a LANL account, then the CIO asks me why the project isn't managed on an internal gitlab server. I've done a few rounds on this and it hasn't been productive so far.

**Comment by davidorville** [comment]
Having said all of this, I'd certainly love to find a way to solve this. If you guys are already using (or know of someone who is using) resources at SNL or LLNL in their restricted networks, that would be a good place for me to start.

**Comment by davidorville** [comment]
By the way, nice to meet you all. :-)

**Comment by Yurlungur** [comment]
Nice to meet you @davidorville! Thanks for the detailed information!

I'm not sure it's practical to give every contributor to this project access to darwin. Would a special branch that is only triggered by people with darwin accounts work? That way we would be vetting any code that makes it into that branch? Or a LANL-internal private github fork?

**Comment by davidorville** [comment]
@Yurlungur Agreed. A special branch might be possible but I'd still need to discuss the access and user mapping with the CIO Cyber Team. An alternative approach might be to have a mirror hosted on the internal gitlab.lanl.gov server by those with LANL accounts and manage CI from there. The logistics might be tricky but if CI is managed from gitlab.lanl.gov server, no approvals are needed and you can just run CI jobs from there using the SLURM batch runner to access Power 9 nodes. As you can imagine, it's the audit trail that matters for things like this. If there is information leakage or some sort of malware incident then the first question is how did this person/job get access to the internal resource.

**Comment by Yurlungur** [comment]
> An alternative approach might be to have a mirror hosted on the internal gitlab.lanl.gov server by those with LANL accounts and manage CI from there. The logistics might be tricky but if CI is managed from gitlab.lanl.gov server, no approvals are needed and you can just run CI jobs from there using the SLURM batch runner to access Power 9 nodes. As you can imagine, it's the audit trail that matters for things like this. If there is information leakage or some sort of malware incident then the first question is how did this person/job get access to the internal resource.

@davidorville I think that solution would work fine.   My sense is that the desire for Darwin is so we can make sure our code runs on architectures we care about. We already have public CI for everything else. What does everyone else think?

**Comment by pgrete** [comment]
This setup would be very similar to what we're currently doing.
The GitLab repo (to which I connected our runners) just mirrors this repo and automatically reports back the results via hooks.
If you setup a similar mirror on the internal LANL GitLab we'd just get another entry in the list of checkmarks for each pull request indicating whether the tests were successful or failed, but GitHub user have no access to the details (similarly to the original private GitLab repo to which I had to add everyone as a member before you were able to view the results).

**Comment by junghans** [comment]
> This setup would be very similar to what we're currently doing.
> The GitLab repo (to which I connected our runners) just mirrors this repo and automatically reports back the results via hooks.
> If you setup a similar mirror on the internal LANL GitLab we'd just get another entry in the list of checkmarks for each pull request indicating whether the tests were successful or failed, but GitHub user have no access to the details (similarly to the original private GitLab repo to which I had to add everyone as a member before you were able to view the results).

The GitHub integration is only part of the gitlab Enterprise edition not the community edition, that we run on Darwin.

**Comment by davidorville** [comment]
We're running 12.9.2-ee on gitlab.lanl.gov right now. It does look like GitHub Integration is a premium feature, though. We'd need to buy the Premium (Silver) option to get it. Would the basic GitLab Webhook support work at all? Alternatively, gitlab.lanl.gov only has some 1,600+ active users (and growing) so maybe someone can fund an upgrade to Premium Edition?

**Comment by Yurlungur** [comment]
Do we actually need hooks and github integration? Can we simply mirror the master branch and run some tests on a schedule? That way Darwin could be used for scheduled tests and @pgrete's server could be used for commit-wise tests. I would be sad to lose what @pgrete put together, since we would then lose the ability for outside collaborators to look at the CI output.

**Comment by pgrete** [comment]
> Do we actually need hooks and github integration? Can we simply mirror the master branch and run some tests on a schedule? That way Darwin could be used for scheduled tests and @pgrete's server could be used for commit-wise tests. I would be sad to lose what @pgrete put together, since we would then lose the ability for outside collaborators to look at the CI output.

That's kind of what I meant with "get another entry in the list of checkmarks", i.e., we'd keep the current tests in place (plus extension with more tests being added) and add another CI test (that includes the Power9 runs) that runs internally at LANL, which only publicly reports back success/fail, but not details.

**Comment by Yurlungur** [comment]
> That's kind of what I meant with "get another entry in the list of checkmarks", i.e., we'd keep the current tests in place (plus extension with more tests being added) and add another CI test (that includes the Power9 runs) that runs internally at LANL, which only publicly reports back success/fail, but not details.

Yeah that would work. It doesn't even have to be some complex, I think, though. If github integration is a blocker, we can simply have a mirror and a schedule. Then those of us on the LANL yellow can get nasty-grams when the nightly build fails.

**Comment by junghans** [comment]
Actually Travis CI has power nodes these days, see https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z
