### ISSUE TITLE
Avoid GLOBs

### ISSUE THREAD

**Issue by jlippuner** [lanl/parthenon#113]
Often times when I switch branches or pull new changes and then run `make` in my build directory, I get something like this:

```
-- GLOB mismatch!
-- GLOB mismatch!
-- GLOB mismatch!
...
```
I'm assuming that's because some file name has changed and CMake made list of files using GLOB. Can we avoid GLOBs in CMake and just list all files explicitly?

**Comment by AndrewGaspar** [comment]
I think the two main places it's used is for are checking file copyrights and formatting.

I really want to make it as difficult as possible to forget to add a copyright to any new file. Having it be part of CMake and using a global makes it very difficult to do this. But if you find another way to do it (via CI or whatever) then we could remove it.

**Comment by Yurlungur** [comment]
I am not a cmake expert, so please forgive me if this is a naive question. If a filename has changed, presumably the  cmake cache is out of date and needs to be regenerated anyway, no? So this mismatch is actually the correct error?

**Comment by AndrewGaspar** [comment]
Yeah, that is correct.

**Comment by JoshuaSBrown** [comment]
@AndrewGaspar I think the ci would probably be a better place for this. I think calling a simple shell script might be a straightforward way of doing this.

**Comment by AndrewGaspar** [comment]
This seems low priority, so I'm going to close it.
