### ISSUE TITLE
UVM doesn't work

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#117]
In preparation of Kokkosizing the remainder of the code I tried creating some reference solution based on the advection test and make sure that without any changes the UVM version give the same results as the OpenMP version.

Unfortunately, it doesn't and the advection example results in 
```
cycle=0 time=0.0000000000000000e+00 dt=0.0000000000000000e+00
cycle=1 time=0.0000000000000000e+00 dt=0.0000000000000000e+00
cycle=2 time=0.0000000000000000e+00 dt=0.0000000000000000e+00
cycle=3 time=0.0000000000000000e+00 dt=0.0000000000000000e+00
cycle=4 time=0.0000000000000000e+00 dt=0.0000000000000000e+00
cycle=5 time=0.0000000000000000e+00 dt=0.0000000000000000e+00
...
```

Good news: the unit tests pass.
I'll try to track this down.

Tagging @jlippuner and @forrestglines for info.

**Comment by Yurlungur** [comment]
@pgrete was this in the branch you're merging in with #116? It could perhaps be related to the implementation of `ParArrayND`'s `GetHostMirrorAndCopy`?

**Comment by pgrete** [comment]
Never mind.
Let's say I found the bug on my end ;)
