### ISSUE TITLE
Driver specific outputs?

### ISSUE THREAD

**Issue by JoshuaSBrown** [lanl/parthenon#119]
In the original athena++ code there was a way for users to define their own inputs which could be written to the supported file formats, that functionality has since been pulled out. Refactors in the code such as the driver class also mean that a new and improved implementation is probably warranted. There is a need for such a feature, for instance in the case of regression testing it would be ideal if parameters specific to each driver were also output in the supported file formats. 

Topics I would like to address in this issue is:

1. Is there much of a need for this functionality outside of testing?
2. If so, how should such a feature be implemented and what functionality would be useful?

**Comment by pgrete** [comment]
I'm not sure I completely understand the connection between the inputs  (" to define their own inputs" ) and outputs ("written to the supported file formats"/"parameters specific to each driver were also output in the supported file formats.").
Are you referring to user defined fields (such like the `one_minus_advected` field in the advection example or referring to the input parameters?

**Comment by JoshuaSBrown** [comment]
Neither, take the calculate pi example, the actual value of pi is not in a user defined field, it is simply printed at the end of the run. It would probably be ideal if it was also output in the existing supported file formats.

**Comment by Yurlungur** [comment]
I'm also not sure I understand. pi is a number, not a field on the grid. Are you suggesting we add the capability to add... I guess metadata? numbers and strings and the like?

**Comment by JoshuaSBrown** [comment]
> I'm also not sure I understand. pi is a number, not a field on the grid. Are you suggesting we add the capability to add... I guess metadata? numbers and strings and the like?

Yes, but only if it is useful.

**Comment by Yurlungur** [comment]
This would be useful, I think. But I'm not sure it belongs in the driver. We probably want the ability to register metadata as output with the IO system itself.

**Comment by AndrewGaspar** [comment]
Seems like there isn't a lot of interest in this feature, so let's close it.
