### ISSUE TITLE
Container Iterator returns a single contiguous view if possible

### ISSUE THREAD

**Issue by Yurlungur** [lanl/parthenon#122]
As discussed on call. I will do this once @jdolence's ContainerIterator solidifies into a single API.

**Comment by Yurlungur** [comment]
Related to issue #90

**Comment by AndrewGaspar** [comment]
@Yurlungur could you elaborate on this?

**Comment by Yurlungur** [comment]
The hope was to have `VariablePack` return a single contentious array if it's only packing one variable. Not sure this is important. I'd say close it for now.
