### ISSUE TITLE
ContainerIterators produce cached, unique view of views if possible.

### ISSUE THREAD

**Issue by Yurlungur** [lanl/parthenon#123]
As discussed on the call. I'll implement this once the ContainerIterator @jdolence implemented solidifies.

**Comment by Yurlungur** [comment]
Related to issue #90

**Comment by nmsriram** [comment]
@yurlunger I'm trying to understand the need for this.  Generating the container is expected to be a pretty inexpensive operation, so would cacheing add complexity for not a lot of gain?

**Comment by Yurlungur** [comment]
@nmsriram  this is something @forrestglines  brought up in the call. The concern is that there’s a cost to allocating the outer view of views which could add up on the gpu. So what needs to be cached isn’t so much the data structure itself as the memory for the outer view.

That said, I’m not actually convinced it will be that difficult to add a caving mechanism.
