### ISSUE TITLE
Kokkos memory error in regression tests in parthenon-cuda-short ci run

### ISSUE THREAD

**Issue by JoshuaSBrown** [lanl/parthenon#129]
The regression tests have already discovered an error when running kokkos. Unfortunately the debug symbols are not being resolved. This issue bears further investigation. 

Here are the build flags that were used

31 $ export OMP_PROC_BIND=close
04:20
32 $ export OMP_PLACES=cores
33 $ export OMP_NUM_THREADS=1
34 $ export CMAKE_VERSION=3.10.3
35 $ export CTEST_OUTPUT_ON_FAILURE=1
36 $ export J=$(( $(nproc --all) / 4  + 1 )) && echo Using ${J} cores during build
37 Using 5 cores during build
38 $ wget -qO- http://www.cmake.org/files/v${CMAKE_VERSION:0:4}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz | tar -xz
39 $ export PATH=${PWD}/cmake-${CMAKE_VERSION}-Linux-x86_64/bin:$PATH
40 $ mkdir build-cuda-debug
41 $ cd build-cuda-debug
42 $ cmake -DCMAKE_BUILD_TYPE=Debug -DHDF5_ROOT=/usr/local/hdf5/parallel -DKokkos_ENABLE_OPENMP=True -DKokkos_ARCH_WSM=True -DKokkos_ENABLE_CUDA=True -DKokkos_ARCH_PASCAL61=True -DCMAKE_CXX_COMPILER=${PWD}/../external/Kokkos/bin/nvcc_wrapper ../ && make -j${J} && ctest -j${J} -LE performance

And here is the error message

'/builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example', '-i', '/builds/pgrete/parthenon/tst/regression/test_suites/calculate_pi/parthinput.regression']
339 [runner-yxoSyTWD-project-17263873-concurrent-0:03259] Error: Unable to get the current working directory
340 [runner-yxoSyTWD-project-17263873-concurrent-0:03259] Error: Unable to get the current working directory
341 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] Error: Unable to get the current working directory
342 Kokkos::View ERROR: attempt to access inaccessible memory space[runner-yxoSyTWD-project-17263873-concurrent-0:03258] *** Process received signal ***
343 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] Signal: Aborted (6)
344 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] Signal code:  (-6)
345 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7fbb43c03890]
346 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7fbb42effe97]
347 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7fbb42f01801]
348 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [ 3] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0xfbbeb)[0x55dde697ebeb]
349 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [ 4] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0x111da)[0x55dde68941da]
350 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [ 5] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0xe15ef)[0x55dde69645ef]
351 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [ 6] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0x77c92)[0x55dde68fac92]
352 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [ 7] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0x3d26c)[0x55dde68c026c]
353 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [ 8] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0x3ba04)[0x55dde68bea04]
354 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [ 9] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0x33ada)[0x55dde68b6ada]
355 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [10] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0x6be00)[0x55dde68eee00]
356 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [11] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0x6aa30)[0x55dde68eda30]
357 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [12] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0x1073d)[0x55dde689373d]
358 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [13] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fbb42ee2b97]
359 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] [14] /builds/pgrete/parthenon/build-cuda-debug/example/calculate_pi/pi-example(+0x1053a)[0x55dde689353a]
360 [runner-yxoSyTWD-project-17263873-concurrent-0:03258] *** End of error message ***

Link to ci output

https://gitlab.com/pgrete/parthenon/-/jobs/528900371#L7

**Comment by pgrete** [comment]
We need UVM fpr Cuda until everything is Kokkosized. This is fixed in #124.
