### ISSUE TITLE
ParArray question

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#135]
Are the Slices of the `ParArray` correct for slices in the first and second dim?
https://github.com/lanl/parthenon/blob/496d8ac94ccaf1bfdbf73739cc0684bffc38f448/src/parthenon_arrays.hpp#L283

The first `Kokkos::ALL()` should also be an SLC0, doesn't it?
Similarly, both `Kokkos::ALL()` for the 1D slice.

**Comment by Yurlungur** [comment]
You are correct. Thanks for the catch! I will submit a MR for a fix.

**Comment by Yurlungur** [comment]
Addressed in issue #137

**Comment by Yurlungur** [comment]
Resolved in #137. Let me know if you find more problems, @pgrete !
