### ISSUE TITLE
Containers with multiple types

### ISSUE THREAD

**Issue by bprather** [lanl/parthenon#141]
In implementing KHARMA, I've run into a couple of cases where I would like to carry around flags (implemented as integers) as part of a container, to be used or heeded as part of several tasks in a list (or even sync'd at boundaries?).  But each stage takes a Container<Real> which can only store, well, Reals.
The same issue might arise in cases where one wants Real=float, but needs a particular field to be in double precision.
Is there a way to broaden Containers so that they can store/iterate through multiple types of Variables?

**Comment by AndrewGaspar** [comment]
I think this still should be done. We should probably remove the template from `Container` and then do run-time type checking on the attached variables, which can be of any type.

**Comment by AndrewGaspar** [comment]
Is this something you're still interested in, @bprather ?

**Comment by Yurlungur** [comment]
Discussed further in #744
