### ISSUE TITLE
Typecasting of `ParArrayND.Get<D>()`

### ISSUE THREAD

**Issue by Yurlungur** [lanl/parthenon#143]
While `kokkos-izing` `Parthenon` @pgrete found some interesting behavior for `ParArrayND` which I'd like to discuss. It's not a bug, exactly, but it raises some questions about a path forward here.

## What's happening?

The basic issue is that, e.g., `ParArrayND.Get<4>();` does **not** return a `ParArray4D<Real>`  object. It returns something close but not quite there. As of now, with the current layout settings, `ParArrayND<Real>.Get<4>()` returns
```C++
 Kokkos::View<double****, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0> >
```
But `ParArray4D` is 
```C++
Kokkos::View<double*****, Kokkos::LayoutRight, Kokkos::HostSpace>
```
Fortunately, the two types are compatible. So you can set one equal to the other and do implicit casts. i.e., the following works:
```C++
void doNothingByValue(ParArray4D<Real> array) {}
ParArrayND<Real> ndarray;
auto b = ndarray.Get<4>();
doNothingByValue(b);
```
But C++ won't do implicit casts on references to variables, so *this* fails:
```C++
void doNothingByReference(ParArray4D<Real>& array) {}
ParArrayND<Real> ndarray;
auto b = ndarray.Get<4>();
doNothingByReference(b);
```

## Why is this happening?

It has to do with `Kokkos::subview`. `ParArrayND` returns whatever type `subview` returns. But `subview` is more specific and specialized, template-wise, than the default `Kokkos::View<Real****,DeviceSpace>`, which is what `ParArray4D` is set to.

## What do we do about it?

In my mind, this means `ParArrayND` is doing the right thing. I see a couple of paths forward, which are all acceptable:
1. Explicitly cast `.Get<4>()` to `ParArray4D` when desired. e.g., the code looks very explicit:
```C++
ParArray4D<Real> b = a.Get<4>();
```
2. Template functions on array type. i.e., functions that take an array are templated as
```C++
template<typename ArrayType>
myFunction(ArrayType &a);
```
3. Pass by value not by reference. (This is safe, since all copies are shallow.) In other words, functions that take `ParArray4D` should always take it by value. This might be slightly slower than passing by reference.
4. Pass `ParArrayND` through as appropriate instead of variables typed by rank.
5. Redefine `ParArray4D` and co. to *explicitly* be subviews of a 6D dynamic size view so that they have *exactly* the same type as the object returned by `ParArrayND`.

Obviously some of these solutions are in tension with what we decided regarding issue #115.

Probably which option is appropriate depends on the code path, and I don't think it's super important. I don't think we need to do anything about this now.  That said, I do think this is worth discussing. What do people think?

Tagging @pgrete @forrestglines @jdolence @jmstone @AndrewGaspar @jlippuner @nmsriram and whoever else is interested.

**Comment by AndrewGaspar** [comment]
I learn towards just doing the explicit casts unless this is polluting the code.

**Comment by Yurlungur** [comment]
That should work fine, I think. I'll close the issue for now. And we can reopen it if it becomes a problem.

**Comment by pgrete** [comment]
How about adding a note to the dev guide (https://github.com/lanl/parthenon/blob/master/docs/development.md) with a link here?

**Comment by Yurlungur** [comment]
> How about adding a note to the dev guide (https://github.com/lanl/parthenon/blob/master/docs/development.md) with a link here?

That's a good idea. I'll submit a MR for that.
