### ISSUE TITLE
Should regression tests and examples be combined?

### ISSUE THREAD

**Issue by JoshuaSBrown** [lanl/parthenon#148]
This is the result of discussion on https://github.com/lanl/parthenon/pull/147. 

In general I don't think they are the same, the examples I believe are trying to show how to use the infrastructure whereas the regression tests are showing that it works correctly. There are cases where the input decks are likely to be very different. You might want to run an example for more time steps to see the end result, whereas it might be sufficient for a test to run it for a single step etc. This should probably go to another issue.

**Comment by Yurlungur** [comment]
I agree. I don't think they're the same. It is possible, even likely, that regression tests will be a subset of the examples. But the way they're run may be very different. I would rather the example directory not be renamed.

**Comment by nmsriram** [comment]
I think we should have separate regression tests and examples. It's OK to have duplication of the driver because the inputs will be vastly different.

**Comment by JoshuaSBrown** [comment]
What do you mean by duplication of the driver? Do you simply mean calling the same driver twice just with different inputs? I would agree with that.

**Comment by AndrewGaspar** [comment]
I think at this point we've decided to keep the examples in an independent folder from the regression test code.
