### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#156]
While adapting the AthenaPK side to work with the current master I noted a performance regression compared to master about two weeks ago.
The performance regression occurs even in the simplest case (static grid, single meshblock).
For reference:
- old: e591c82b zone-cycles/omp_wsecond = 2.0160420384343944e+07
- new 548baeb zone-cycles/omp_wsecond = 1.1736363478388650e+07

Using a single AMD EPYC 7552 core compiled with clang version 11.0.0 and `cmake -DCMAKE_BUILD_TYPE=Release -DKokkos_ARCH_EPYC=True  -DKokkos_ENABLE_OPENMP=True ../`

It'd be great of other people could confirm that regression (or if I'm seeing ghosts and/or have a ghost in the machine).

For reference here's the old input file:
```
<comment>
problem = Linear advection

<job>
problem_id = advection

<mesh>
refinement = none
numlevel = 3

nx1 = 64
x1min = -0.5
x1max = 0.5
ix1_bc = periodic
ox1_bc = periodic

nx2 = 64
x2min = -0.5
x2max = 0.5
ix2_bc = periodic
ox2_bc = periodic

nx3 = 64
x3min = -0.5
x3max = 0.5
ix3_bc = periodic
ox3_bc = periodic


<meshblock>
nx1 = 64
nx2 = 64
nx3 = 64

<time>
tlim = 100.0
nlim = 300
integrator = rk2

<Advection>
cfl = 0.30
vx = 1.0
vy = 1.0
refine_tol = 0.3    # control the package specific refinement tagging function
derefine_tol = 0.03
```

and the new one:
```
<parthenon/job>
problem_id = advection

<parthenon/mesh>
refinement = none
numlevel = 3

nx1 = 64
x1min = -0.5
x1max = 0.5
ix1_bc = periodic
ox1_bc = periodic

nx2 = 64
x2min = -0.5
x2max = 0.5
ix2_bc = periodic
ox2_bc = periodic

nx3 = 64
x3min = -0.5
x3max = 0.5
ix3_bc = periodic
ox3_bc = periodic

<parthenon/meshblock>
nx1 = 64
nx2 = 64
nx3 = 64

<parthenon/time>
tlim = 100.0
nlim = 300
integrator = rk2

<Advection>
cfl = 0.30
vx = 1.0
vy = 1.0
refine_tol = 0.3    # control the package specific refinement tagging function
derefine_tol = 0.03
```

**Comment by forrestglines** [comment]
I tested these two commits and master on the advection example on one core using the Intel Skylakes on Pleiades ( Intel Xeon Gold 6148). I didn't see much difference between these two commits, but I did see a large speed up with master.

```
b9caeda4017bea108824bcba3793c654dacc1c13 (master)
zone-cycles/omp_wsecond = 2.8239318983967155e+07

548baeb6923e5c6fb2ebb42a6eeeebb65383ddea ("new")
zone-cycles/omp_wsecond = 1.1985879026307063e+07

e591c82b626c9ed606a566813e5f8ef7df6e3ac9 ("old")
zone-cycles/omp_wsecond = 1.1287315916048991e+07
```

I compiled with
```
CMAKE_CXX_FLAGS="-O3 -inline-forceinline -qopenmp-simd -qopt-prefetch=4 -diag-disable 3180 "
```

However, I was not able to use `-ipo` was I normally would since the Intel compiler would run out of memory, even on a dedicated node.

**Comment by pgrete** [comment]
Interesting. Thanks for double checking.
I also tried on Pleiades (not providing any additional optimization flags, just using the Release `-03`) and got
```
master: zone-cycles/omp_wsecond = 2.8469416163725246e+07
new: zone-cycles/omp_wsecond = 1.1997830568301234e+07
old: zone-cycles/omp_wsecond = 1.5131758830472603e+07
```

While I now understand the difference between "old" and "new" (turns out this actually was a ghost as the "old" version didn't include a calculation of the z fluxes but it was a 3D problem), it still very interesting that master is that much faster.
We should definitely keep an eye on performance

Anyone interested in implemented performance regression tests?

**Comment by jdolence** [comment]
I’m not interested in doing it myself per se, but I second the suggestion that we need performance regression tests.

**Comment by Yurlungur** [comment]
Outdated
