### ISSUE TITLE
Split Container Iterator into two tests

### ISSUE THREAD

**Issue by JoshuaSBrown** [lanl/parthenon#158]
Unit tests should probably be limited to running for less than 5s, this test takes longer as it has a performance component. It would be best to probably split the test in two, a performance component and a unit testing component.

**Comment by Yurlungur** [comment]
Actually this leads to a longer discussion.

I would like to move to a model where we have per-commit tests that run quickly and slower tests, including performance tests, tests in debug mode, and bigger regression tests that are run on a schedule, say nightly. 

Interested in people's thoughts on that.

**Comment by JoshuaSBrown** [comment]
Well I'm for this, I think that @AndrewGaspar was of the thought that we could run in depth tests everytime master is updated.
