### ISSUE TITLE
HDF5 output

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#160]
HDF5 files produced with current master cannot be processed (more precisely the xdmf file seems to be off) resulting in
```
Warning: In /build/paraview/src/ParaView-v5.8.0/VTK/Common/DataModel/vtkDataSet.cxx, line 695
vtkRectilinearGrid (0x55a2ffc20f90): Cell array cons with 3 components, has 109226 tuples but there are only 65536 cells
```
when being read with Paraview (disclaimer, we're using a single `Variable` to store all physical variables.

In addition, the python plotting script also seem to be off when using AMR, e.g.,
![0002](https://user-images.githubusercontent.com/22685568/81659898-729b0f00-943a-11ea-9795-3090c207b7d7.png)
(I'm hoping it's just the plotting).
The only change I made was an adaption to the plotting script to plot the first variable of our variable vector:
```diff
diff --git a/scripts/python/movie2d.py b/scripts/python/movie2d.py
index 578ec40..9b384a3 100644
--- a/scripts/python/movie2d.py
+++ b/scripts/python/movie2d.py
@@ -55,7 +55,7 @@ if __name__ == "__main__":
         print(data)
         xf = data.xf
         yf = data.yf
-        q = data.Get(field,False)
+        q = data.Get(field,False)[:,:,:,:,0]
         name = str(dump_id).rjust(4,'0') + ".png"
         plot_dump(xf, yf, q, name, True)
         dump_id += 1
```

**Comment by pgrete** [comment]
This does seem go beyond the python script.
The following image shows the same quantity plotted with ParaView (I created a new derived scalar variable that ParaView is able to display out of the box with current master):
![Screenshot from 2020-05-12 11-53-13](https://user-images.githubusercontent.com/22685568/81670033-55207200-9447-11ea-9334-a7405182edd8.png)

**Comment by pgrete** [comment]
Hold on. I may have an AMR related issue in my code.
(However, this only pertains to the plotting. Paraview with Variable vectors still doesn't work).

**Comment by nmsriram** [comment]
I'll take a look at this.

**Comment by nmsriram** [comment]
@pgrete can you provide me an example? 
I can't make this happen with the advect example.

![advectMesh 0009](https://user-images.githubusercontent.com/1276138/81715563-9c056c00-9435-11ea-8e57-cb6ddcff5bd3.png)
![advect 0009](https://user-images.githubusercontent.com/1276138/81715588-a0ca2000-9435-11ea-8fe7-5479c72a33f4.png)

**Comment by nmsriram** [comment]
Just realized I only ran in serial.  Will try parallel.

**Comment by pgrete** [comment]
The output of a scalar `Variable` seems to work for me, too.
The problem in storing a vector (i.e., multiple scalar variables) in a single `Variable`, e.g., in the advection example make the "advected" quantity have "2" as the nth dimension.

**Comment by nmsriram** [comment]
Checked parallel and it works as well.
I'm using the plain XDMFReader

**Comment by nmsriram** [comment]
@pgrete can you provide me an example?  I used the advection example as is and with 4 as third dimension.  and it worked.  I'm using preview V5.7.0

**Comment by nmsriram** [comment]
I also ran advection example in serial and parallel.

**Comment by nmsriram** [comment]
@pgrete @jdolence reproduced problem and will send me something I can look at.  Stay tuned...

**Comment by nmsriram** [comment]
@pgrete I downloaded and tested the code and #163 fixes this issue by splitting multi-dimensional non-vector fields into their appropriately named scalar components.

**Comment by pgrete** [comment]
I can confirm this. Thanks for taking care of this so quickly.
