### ISSUE TITLE
Regression test don't differentiate between MPI and non-MPI runs

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#164]
In fact, we only ever compile for MPI though Parthenon also works without MPI.
Thus, this should be reflected in the (regression) tests and would also reduce runtime of tests.

**Comment by JoshuaSBrown** [comment]
I don't completely follow, currently the default in the regression tests is to run with a single processor and with a default number of processors which is 4 if mpi is found (The default number of processors can be changed with a cmake flag, NUM_MPI_PROC_TESTING). Are you suggesting instead that if mpi is found run only once? 

I guess you could do something like this if you wanted to test the regression tests on different numbers of processors. This would also let us cleanup the CMake files. 
  
```
cmake -DNUM_MPI_PROC_TESTING=1 ../
ctest -R regression
cmake -DNUM_MPI_PROC_TESTING=4 ../
ctest -R regression
```

Are you also suggesting building without MPI? This would probably be a good idea. It doesn't look like any of the ci builds are currently doing this.

**Comment by pgrete** [comment]
> Are you also suggesting building without MPI? This would probably be a good idea. It doesn't look like any of the ci builds are currently doing this.

Yes, that is my main point (sorry I wasn't clear in first place). As you say we're currently always building with MPI but have many place in the code which take different paths depending whether one builds with or without MPI (independent of whether you run with one or n processes).
Thus, we should test all cases.
I expect this to be a straightforward addition once the implementation of the convergence tests is completed. #165

**Comment by JoshuaSBrown** [comment]
This has been addressed from what I can see in the ci files.
