### ISSUE TITLE
Moving regression and performance testing to different CI stage?

### ISSUE THREAD

**Issue by JoshuaSBrown** [lanl/parthenon#166]
I think it would be a good idea as we add regression tests to move them to a different stage in the ci particularly given that the performance and regression tests are time intensive. If the unit and integration testing is done before a lot of bugs can be caught quickly without eating up a lot of the compute resources in the performance and regression testing runs.

**Comment by pgrete** [comment]
Overall I think this is a good idea. I'd probably keep one/a few short regression tests during the initial stage in order to catch errors raised by the embedded debug features.
