### ISSUE TITLE
Code formatter version/problem/...?

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#173]
@AndrewGaspar why is https://github.com/lanl/parthenon/pull/165/checks?check_run_id=700073402 reporting failure?
When I run `make format` on my machine the code seems to be fine.

**Comment by AndrewGaspar** [comment]
Are you using clang-format 8? Run `clang-format --version`.

**Comment by pgrete** [comment]
I'm using a newer version (10.0.0). I'll keep that in mind though I'm still surprised that for a given `.clang-format` definition results are different between versions.

**Comment by AndrewGaspar** [comment]
Yeah, it's unfortunate. :(

**Comment by AndrewGaspar** [comment]
There should be a warning when you configure if you have a different clang-format.
