### ISSUE TITLE
ParArrayND needs to expose meshblock to use the appropriate deep copy operation

### ISSUE THREAD

**Issue by Yurlungur** [lanl/parthenon#178]
As pointed out by @pgrete in #136

**Comment by AndrewGaspar** [comment]
@Yurlungur Could you expand?

**Comment by Yurlungur** [comment]
The idea is to expose a `ParArrayND.DeepCopy(src, meshblock);` so it uses the correct meshblock's stream. I don't think this is urgent. (And @pgrete may have just implemented it already.) Let's close for now.

**Comment by pgrete** [comment]
Yeah, the current workaround is to use the exec space as argument in DeepCopy (however, that introduced the ugly work around for the buffer packing unit test that doesn't have a MeshBlock)
