### ISSUE TITLE
Use of `IndexRange` in buffer `par_for` and friends

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#183]
@JoshuaSBrown pointed out that the buffer packing functions currently take all indices as individual arguments.
Using `IndexRange`s would make this code cleaner and could be introduced the next time the buffer packing functions are touched.

Related question (as I missed the discussion in the original PR):
Is there a reason the indexranges are unique for the individual dimensions?
As far as I can tell the majority of functions loops over 3 (or 4) indices, thus having a single struct would simplify/cleanup the code even further, e.g.,  instead of
```
  IndexRange ib = pmb->cellbounds.GetBoundsI(IndexDomain::entire);
  IndexRange jb = pmb->cellbounds.GetBoundsJ(IndexDomain::entire);
  IndexRange kb = pmb->cellbounds.GetBoundsK(IndexDomain::entire);
  for (int k = kb.s; k <= kb.e; k++) {
    for (int j = jb.s; j <= jb.e; j++) {
      for (int i = ib.s; i <= ib.e; i++) {
```
```
  IndexRange b = pmb->cellbounds.GetBounds(IndexDomain::entire);
  for (int k = b.ks; k <= b.ke; k++) {
    for (int j = b.js; j <= b.je; j++) {
      for (int i = b.is; i <= b.ie; i++) {
```

**Comment by AndrewGaspar** [comment]
@nmsriram upvoted this in #190

**Comment by Yurlungur** [comment]
See #185
