### ISSUE TITLE
Auto detect number of required iterations to get accurate benchmark on kokkos kernel and Kokkos Kernel launch

### ISSUE THREAD

**Issue by JoshuaSBrown** [lanl/parthenon#198]
Catch2 does not provide the functionality to run benchmark tests that account for the overhead associated with a kernel launch. It would be idea to be able to calculate the required number of iterations to achieve consistent results. It would also be nice to have a benchmark that measures the kokkos kernel launch latency.

**Comment by Yurlungur** [comment]
We roll our own performance regression tests
