### ISSUE TITLE
Install option for building as standalone library

### ISSUE THREAD

**Issue by brryan** [lanl/parthenon#207]
Right now my understanding is that to use parthenon in an application one must bring in the source code as e.g. a `git submodule` and then build parthenon and the application together. It could be nice to be able to add an install option to the cmake build system so one can just link in a standalone parthenon install. Three ways this could be convenient:
* A physics code built out of two parthenon-based packages doesn't have to worry about each of these packages having their own parthenon source via two `git submodule`s.
* Not having to worry about parthenon's build rules, as in #206 
* Allowing for `spack install parthenon` :)
This may have already been brought up before but I didn't see an open issue and #206 reminded me of this.

**Comment by JoshuaSBrown** [comment]
Are you suggesting a precompiled shared library and or a spack implementation?

**Comment by Yurlungur** [comment]
I think @brryan is suggesting that the former enables the latter.

**Comment by brryan** [comment]
@Yurlungur @JoshuaSBrown Yes once Parthenon can be built as a shared library, I think adding spack support should just be a ~20 line PR to the spack repository.

**Comment by AndrewGaspar** [comment]
Yeah, if you have a "standard" CMake package (at least as standard you can get in a turing complete build system), adding it to Spack is trivial.

**Comment by Yurlungur** [comment]
Not only is this possible, we're considering disabling it.
