### ISSUE TITLE
Labels for different tests. 

### ISSUE THREAD

**Issue by JoshuaSBrown** [lanl/parthenon#209]
It would probably be a good idea to clarify labels for the different tests that can be run and when they should apply. I would like to propose and open to discussion what cmake/Catch2 labels should be used with a given test. 

[unit] - when testing the correctness of a standalone unit of code, should not take more than 5s to run for any single test.
[performance/benchmarking] - for testing the performance of any part of the code base. 
[integration] - Testing the correctness of two or more parts of the code. 
[regression] - It seems that we are currently using this label when testing the correctness/performance of the code base as a whole.
[mpi-yes] - Running with mpi
[mpi-no] - Running without mpi

**Comment by JoshuaSBrown** [comment]
[This is partly related](https://github.com/lanl/parthenon/issues/158)

**Comment by Yurlungur** [comment]
I prefer `performance` over `benchmarking`. But I agree. This is a good idea.

**Comment by Yurlungur** [comment]
Resolved
