### ISSUE TITLE
Improve FindMeshBlock performance

### ISSUE THREAD

**Issue by AndrewGaspar** [lanl/parthenon#211]
See: https://github.com/PrincetonUniversity/athena-public-version/issues/32

**Comment by AndrewGaspar** [comment]
@jmstone Unfortunately it doesn't appear that the current release of https://github.com/PrincetonUniversity/athena-public-version has this change.

**Comment by jmstone** [comment]
Yes, it is only implemented in the development version, to which I thought people (pgrete?) had access.  If not we will update the public version shortly, or you could ask Kengo Tomida for a copy of the relevant files (I hate to share things out of the private repo without the major contributors knowledge).

**Comment by AndrewGaspar** [comment]
@pgrete Could you share that patch?

**Comment by pgrete** [comment]
I sent it via mail two days ago. I'm trying again now. Please let me know if it doesn't show up in your inbox.

**Comment by Yurlungur** [comment]
I am attempting to address this in my PR #303
