### ISSUE TITLE
Holes in test coverage

### ISSUE THREAD

**Issue by JoshuaSBrown** [lanl/parthenon#217]
Currently, a test for the face fields example driver is missing. Adding one would make the testing framework more robust and provide a better idea of where we are missing testing coverage.

**Comment by Yurlungur** [comment]
I can try and take a look at this at some point if no one else volunteers.

**Comment by pgrete** [comment]
Just to add what's missing I think that the reconstruction functions also are a larger block of code that is not fully covered.

**Comment by forrestglines** [comment]
Outdated since the old face centered fields were removed in preparation for the new implementation.
