### ISSUE TITLE
Buffer Packing Kernel

### ISSUE THREAD

**Issue by forrestglines** [lanl/parthenon#221]
After performance discussions in #189, we're fairly confident that the launch overhead from launching one kernel for each buffer of communicated ghostzones is hampering performance when using small ( less than 256^3) meshblocks. One solution would be to combine the packing and unpacking of each buffer into a single kernel for packing all buffers and a single kernel for unpacking all buffers. We can discuss and share solutions here.

We can also start with a kernel for just uniform grids, packing the 6 faces, 12 edges, and 8 corners of a box into 26 buffers. With AMR there are 57 buffers. Note that for the face-centered variables, the box will not necessarily be a cube; the box might be one longer along an axis.

**Comment by forrestglines** [comment]
@pgrete @jmstone Here's the issue to collaborate on the buffer packing kernels. 

My unfinished kernel to do the buffer packing in CUDA is here:

https://github.com/forrestglines/buffer_packing/blob/master/tests/cuda_buffer_packing/cuda_buffer_packing.cu

I started with a version in CUDA since I wanted to be exactly sure of how the kernel was being parallelized. After getting that working, I was planning on moving it to Kokkos.

**Comment by pgrete** [comment]
Ping @cielling @gshipman 
This is where input by Nvidia folks would be great. Efficient ghost zone/guard cell/buffer packing functions are likely a solved problem.

**Comment by pgrete** [comment]
What's the status here? IIRC we discussed on Wednesday to make a minor update here and then ask for help?

**Comment by forrestglines** [comment]
@pgrete Sorry, I got caught up in other projects. My first attempt doesn't work - it was running out of shared memory at larger sizes and I can't figure out some bugs at smaller sizes. I'm taking a simpler approach that I hope to have ready today.

**Comment by forrestglines** [comment]
I have an almost entirely working packing function running with Kokkos at 
https://github.com/forrestglines/buffer_packing/blob/master/tests/kokkos_buffer_packing/kokkos_buffer_packing.cpp

The packing kernel works fine and matches a cpp version for all grid sizes on CPUs and grid sizes up to 64. For larger grids, Kokkos seems to be using a larger thread block size than is supported by the device - I don't know why. The parthenon wrappers might avoid the issue.


Timing looks like this:

![image](https://user-images.githubusercontent.com/5799640/88029575-2dfdb500-cb08-11ea-960d-2b39830cbe9f.png)

It looks like it's dominated by overhead at small grid sizes. Time should scale as nx^2 at larger sizes.

**Comment by pgrete** [comment]
This looks far better than what we have right now.
I think this is a good baseline to touch base with an expert at Nvidia.
@gshipman what's the best way forward to get in touch with someone?

**Comment by forrestglines** [comment]
@pgrete @gshipman  I think one thing that would be helpful would be to have a full description of what the buffer packing functions need to do, even if it's only for uniform grids. I can get that done today or tomorrow, depending on my other projects. It would be best to get in contact with NVIDIA soonish.

I also haven't written the inverse kernel, the unpacking function. However, I think that will be more straightforward now that we have a packing kernel.

**Comment by AndrewGaspar** [comment]
I can't remember if we've discussed this before: Does the use of MPI datatypes offer a potential performance optimization here - i.e. just hand MPI the original buffers without having to do any packing at all? Or is it not viable for this use case?

**Comment by pgrete** [comment]
Are you thinking of `MPI_Pack` etc. here? I'm not sure  if these calls are "Cuda aware" in a performant way. Could be sth to investigate/ask the GPU experts.

**Comment by pgrete** [comment]
https://pdfs.semanticscholar.org/918d/8cfc2f2a2ac26acb9d73ec5e89bf154ed474.pdf <- may be worth having a closer look. Came across it when looking for MPI_Pack and GPU support.

**Comment by AndrewGaspar** [comment]
Oh, I'm referring to the `MPI_Type_*` APIs: http://www.cs.kent.edu/~farrell/cc03/lectures/mpi_datatypes-4.pdf

You presumably could construct an `MPI_Datatype` that describes the ghost cells or boundary cells for a block, which would allow you to send and receive directly from those portions of the vector, potentially obviating the need for a packing kernel at all.

**Comment by gshipman** [comment]
@pgrete we can work with Max Katz (NVIDIA) on performance analysis next week. He is very familiar with buffer packing based on our discussions with him.

**Comment by forrestglines** [comment]
> Oh, I'm referring to the `MPI_Type_*` APIs: http://www.cs.kent.edu/~farrell/cc03/lectures/mpi_datatypes-4.pdf
> 
> You presumably could construct an `MPI_Datatype` that describes the ghost cells or boundary cells for a block, which would allow you to send and receive directly from those portions of the vector, potentially obviating the need for a packing kernel at all.

How complex can the striding be? It would also be different for every buffer. We would also have to be wary of how the MPI library implements it for GPUs, if it's supported at all. I'm not sure if making a separate CUDA API call for each buffer would help in our case.

**Comment by forrestglines** [comment]
> > Oh, I'm referring to the `MPI_Type_*` APIs: http://www.cs.kent.edu/~farrell/cc03/lectures/mpi_datatypes-4.pdf
> > You presumably could construct an `MPI_Datatype` that describes the ghost cells or boundary cells for a block, which would allow you to send and receive directly from those portions of the vector, potentially obviating the need for a packing kernel at all.
> 
> How complex can the striding be? It would also be different for every buffer. We would also have to be wary of how the MPI library implements it for GPUs, if it's supported at all. I'm not sure if making a separate CUDA API call for each buffer would help in our case.



> we can work with Max Katz (NVIDIA) on performance analysis next week. He is very familiar with buffer packing based on our discussions with him.

That would be great - I'm halfway through implementing the inverse operation for buffer packing. I'm reasonably happy performance wise for small mesh blocks with what I currently have, but it likely could be accelerated for large +64 meshblocks.

**Comment by forrestglines** [comment]
> https://pdfs.semanticscholar.org/918d/8cfc2f2a2ac26acb9d73ec5e89bf154ed474.pdf <- may be worth having a closer look. Came across it when looking for MPI_Pack and GPU support.

I peeked through this as best I could - the interface is a little verbose, but we could work with it if we were ok with adding a dependency like this. What I couldn't tell though was how optimized this would be for small meshes. They use manual kernels for packing buffers on the GPU (since MPI_Pack is supposedly slow), but I don't know if they collect many buffers at once in a single kernel call.

**Comment by AndrewGaspar** [comment]
> How complex can the striding be? It would also be different for every buffer. We would also have to be wary of how the MPI library implements it for GPUs, if it's supported at all. I'm not sure if making a separate CUDA API call for each buffer would help in our case.

It can be completely arbitrary using [`MPI_Type_create_struct`](https://docs.microsoft.com/en-us/message-passing-interface/mpi-type-create-struct-function).

Would it be different for every buffer? Every block has the same shape, right? So you really only have to create the `MPI_Datatype` once.

But yes, the big question is whether the MPI implementations actually do something efficient there - I wouldn't bet that it's more efficient than doing buffer packing.

**Comment by AndrewGaspar** [comment]
I suppose it's not right to say there's only one `MPI_Datatype` - you'd have to implement one for each different halo intersection. Hm... yes it would be complicated, haha. Haven't thought this well enough to be able to defend it.

**Comment by forrestglines** [comment]
I have a prototype of the unpacking function working.  Small mesh block speeds look like they're limited by kernel launching overhead, performance on large mesh block sizes could probably be improved.

![image](https://user-images.githubusercontent.com/5799640/89456040-4210fb80-d731-11ea-9359-f6ed6c227b56.png)

**Comment by forrestglines** [comment]
Outdated with current buffer packing
