### ISSUE TITLE
Downstream testing environment

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#222]
@JoshuaSBrown do you have a working example on how to reuse the existing Parthenon testing infrastructure (especially the python based regression tests) in a downstream code?

**Comment by JoshuaSBrown** [comment]
> @JoshuaSBrown do you have a working example on how to reuse the existing Parthenon testing infrastructure (especially the python based regression tests) in a downstream code?

Just to clarify do you mean if you using parthenon as a submodule in another repo and you want to run the regression tests? Or do you mean how to reuse the python script to create tests?

**Comment by pgrete** [comment]
I want to reuse the infrastructure (just running the test in the compiled parthenon module works out of the box).
More specifically, we'd like to run tests similar to the current regression tests i.e, tests that are analyzed by the python framework you added (which is why I pinged you).
So the question is how to tap into the existing framework, e.g., calling `setup_test` outside of the parthenon directory.

**Comment by JoshuaSBrown** [comment]
> I want to reuse the infrastructure (just running the test in the compiled parthenon module works out of the box).
> More specifically, we'd like to run tests similar to the current regression tests i.e, tests that are analyzed by the python framework you added (which is why I pinged you).
> So the question is how to tap into the existing framework, e.g., calling `setup_test` outside of the parthenon directory.

Ok, I think I understand, I think probably the best way to more forward would be to pull all of the python scripts out of /tst/regression and place them in a separate regression-testing-infrastructure folder with the supporting cmake files. The testing infrastructure could then be in essence treated as an independent entity. Right now, the the python test case files are fairly integrated with cmake and the folder structure of parthenon which would make it a little challenging to make use of the infrastructure outside of parthenon. This can of course be refactored. 

Does this sound correct?

**Comment by pgrete** [comment]
Yes, that's what my questions was getting at.
I wanted to check if you'd already done sth like that your the LANL downstream codes so that we don't reinvent the wheel.
@jdolence are you reusing the test suite for your downstream code?

**Comment by JoshuaSBrown** [comment]
I believe the downstream codes we have already have their own testing infrastructure.
