### ISSUE TITLE
Improving Catch2 benchmarking features with Kokkos

### ISSUE THREAD

**Issue by JoshuaSBrown** [lanl/parthenon#223]
Before looking into this further, I wanted to find out how much of a benefit this would be to our team. From what I have seen thus far Catch2 only has limited supported for benchmarking. It would be nice to have extra feature capabilities, for instance the ability to measure the bandwidth. However, before going down this road and looking into adding something, I wanted to know what capabilities would be useful and who would find it useful?

**Comment by Yurlungur** [comment]
One thing that occurs to me is being able to time individual kernels we know are important would be quite useful
