### ISSUE TITLE
Pass ParthenonManager to drivers?

### ISSUE THREAD

**Issue by brryan** [lanl/parthenon#229]
Currently `unique_ptr` components of `ParthenonManager` have their pointers retrieved and passed separately to `Driver` classes. In PR #214 this is three separate pointers from the same class. It might be better, as @Yurlungur points out, to just pass a smart pointer/reference to `ParthenonManager` to the driver itself. One potential complication is not being able to mix and match Mesh/Parameter classes.

**Comment by AndrewGaspar** [comment]
I seem to recall that `ParthenonManager` was meant to be a "utility class" or something of the sort. @jdolence ?

**Comment by AndrewGaspar** [comment]
And, it being a "utility class", wasn't supposed to pollute the public API of parthenon. Like, you should be able to initialize your classes a different way.

**Comment by AndrewGaspar** [comment]
If this is done, this needs to be optional. The EAP integration of Parthenon does NOT use `ParthenonManager`, and it imposes requirements that EAP does not need. Therefore, please ensure that passing `ParthenonManager` is optional.

@brryan - is this still important to you?

**Comment by brryan** [comment]
@AndrewGaspar Since `ApplicationInput` is passed separately to e.g. `Mesh`, I don't see any reason on my end that `ParthenonManager` should be required.
