### ISSUE TITLE
Testing when submodule

### ISSUE THREAD

**Issue by berselius** [lanl/parthenon#233]
I just updated parthenon and am now getting the following error when building it as part of my application

```
CMake Error at parthenon/tst/regression/CMakeLists.txt:15 (include):
  include could not find load file:

    /home/haack/EAP/zapp/cmake/TestSetup.cmake


CMake Error at parthenon/tst/regression/CMakeLists.txt:57 (setup_test):
  Unknown CMake command "setup_test".
```

I'm reading this as Parthenon trying to build some tests and getting confused by the directory structure. Or am I not configuring something correctly.

**Comment by berselius** [comment]
Nevermind, I think my environment got weird somehow. This didn't happen after starting a fresh shell.

**Comment by berselius** [comment]
Oh, I guess what I did was to revert to an older version of the submodule. When I try building with parthenon master, I get the above error.

**Comment by JoshuaSBrown** [comment]
Ok, I think I know what the problem is. The wrong CMAKE path variable appears to be used.

**Comment by JoshuaSBrown** [comment]
As a temporary fix try replacing this line 

```
include(${CMAKE_SOURCE_DIR}/cmake/TestSetup.cmake)
```

with 

```
include(${PROJECT_SOURCE_DIR}/cmake/TestSetup.cmake)
```

in file parthenon/tst/regression/CMakeLists.txt

**Comment by JoshuaSBrown** [comment]
@berselius let me know if it works and thanks for bringing it to our attention.

**Comment by berselius** [comment]
Looks like that did the trick - thanks!
