### ISSUE TITLE
Kokkos integration

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#31]
Opening this issue to keep track of various todos related to the Kokkos integration as I expect this going to be a gradual integration rather a one PR fits all commit.

- [x] Add Kokkos as submodule incl integration
- [x] Add loop wrapper for any dimension
- [ ] Add TeamThreadRange abstraction
- [x] Add nested wrappers
- [x] Replace AthenaArrays with Kokkos Views (fixed dimensional typedefs)
- [x] Add tests for all wrappers
- [x] Add support for ExecutionSpaces (streams) to MeshBlocks (par_for and deep_copy)
- [x] Add support for `partition_manager` to task management
- [ ] Make sure all wrapper options are sane (there was some discussion at the workshop on using/not using TeamThreadRanges and or ThreadVectorRanges on GPUs -- need to dig out my notes)
- [x] Document usage
- [x] Add performance regression infrastructure (potentially independent of this)

**Comment by pgrete** [comment]
Reposting some info on MPI usage @crtrott mentioned on the Slack channel to keep track:
```
the only issue is if you do MPI after the deep_copy
10:38
deep_copy(CUDA(),device,host); MPI_Recv(device.data(),...);
10:38
would be bad
10:38
host.data() I mena
10:39
since the MPI overwrites the data while the copy is still in flight
10:39
basically you could always do deep_copy(Cuda(),...); and then just do Cuda().fence() before you touch the host data the next time
10:40
that would still be less fencing than deep_copy(…);
10:40 PM
Doesn't have to be MPI, does it.  Any CPU touching of the host view would be a problem, right?
10:40 PM
yeah
10:41
but in either case deep_copy(Cuda(),a,b); Cuda().fence(); is always strictly faster than deep_copy(a,b);
10:42
the only issue is if you ever compile with an asynchronous Host backend
10:42
then everything explodes
10:43 PM
because parallel_for(RangePolicy<AsycnHost>(0,n),fill(host)); deep_copy(Cuda(),b,host); Cuda()fence(); needs an additional AsyncHost().fence();
10:44
on the other hand DefaultHostExecutionSpace().fence() is practically a no-op right now
10:45
so you could always do this: DefaultHostExecutionSpace().fence(); deep_copy(DefaultExecutionSpace(),a,b); DefaultExecutionSpace().fence();
10:45
in a situation where you do not have any non-default exec space instances this is I think semantically the same as deep_copy(a,b);
10:46
and it would only give you a single cudaStreamSycnhronize
10:46
as the only fnece
```

**Comment by AndrewGaspar** [comment]
@pgrete Can we close this issue or separate out the sub-tasks into their own issues - seems like it might be a bit stale?

**Comment by pgrete** [comment]
Agreed. And we also don't need to create new issues. All the key pieces are effectively addressed.
