### ISSUE TITLE
Open parthenon to the public

### ISSUE THREAD

**Issue by gshipman** [lanl/parthenon#45]
Hi folks, any remaining issues need to be resolved (renaming, squashing commits, etc..) prior to opening up parthenon?

**Comment by gshipman** [comment]
We are a public repo.

**Comment by Yurlungur** [comment]
🥂

**Comment by junghans** [comment]
Please switch the CI to public as well.

**Comment by Yurlungur** [comment]
> Please switch the CI to public as well.

@pgrete ?

**Comment by pgrete** [comment]
Done.
