### ISSUE TITLE
Support restarts

### ISSUE THREAD

**Issue by jdolence** [lanl/parthenon#61]
Currently restarting a simulation is broken, but is obviously required functionality.

**Comment by JoshuaSBrown** [comment]
So before moving forward with this it would probably be a good idea to know what the problems with the Athena++ implementation. Is it desirable to keep a similar file format to what was available previously? Or is the issue how to integrate the restart capability in the code base seeing as the infrastructure has changed?

**Comment by Yurlungur** [comment]
> So before moving forward with this it would probably be a good idea to know what the problems with the Athena++ implementation. Is it desirable to keep a similar file format to what was available previously?

There are no problems with the Athena++ implementation, I think. It's desirable to keep it.

> Or is the issue how to integrate the restart capability in the code base seeing as the infrastructure has changed?

Exactly. We broke it when we wrote all the interface stuff. So all that's needed is to dig in and hook it up again. I think it's just a matter of sitting down and doing so.

**Comment by Yurlungur** [comment]
Can we close this? Or not yet?

**Comment by nmsriram** [comment]
#311 fixes this partially.  Serial restarts work, parallel restarts work on same number of processes or fewer.  

Still fixing: 
 - Parallel restarts with more than the original number of processors
 - LANL physics code shows machine-precision level differences

**Comment by nmsriram** [comment]
#311 fixes this issue completely.

**Comment by Yurlungur** [comment]
Closing the issue.
