### ISSUE TITLE
Containers/Variables/AthenaArrays design

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#64]
While working on the Kokkos integration I noticed that the Containers/Variables are derived from the AthenaArray class.
If I remember our discussion at the workshop correctly, we decided that don't need the AthenaArray class any more and will directly use Kokkos::Views as they provide the same functionality (e.g. shallow copies and slices).
In addition, all arrays would get a fixed size which makes many interfaces cleaner/more descriptive and also remove a lot of boilerplate in redefining local variables.
In #34 these are currently defined as https://github.com/lanl/parthenon/blob/3a565b50871f5583a417a90a2bf5db7de381e695/src/kokkos_abstraction.hpp#L41

Thus, the question is now we want to proceed from here as the design choice will have implication on application design.

From my point of view, I conceptually understand a `Variable` to contain a `Kokkos:View` (i.e., a `ParArrayND`)  plus additional information, and a `Container` holds `Variables`.
At the application level I see that information from `Containers` and `Variables` would be used at higher, more generic levels in the code (e.g., output generation) whereas the lower level functions that directly solve equations would primarily use the `ParArrayND`s in their interfaces.

(Ping @forrestglines @jmstone @AndrewGaspar @JoshuaSBrown @jdolence @jlippuner @Yurlungur )

**Comment by jdolence** [comment]
I think this is resolved adequately for now via #75 #76 #65.
