### ISSUE TITLE
Template specialization for problem generators?

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#71]
We (Athena Physics) would like to be able to be able to compile a single executable that includes all kind of integrators and problem types implemented.
Therefore, it'd be great if we could add template specialization to the MeshBlock functions such as ProblemGenerator.
Is that sth that would be useful for other applications, too, or would this go against some design decisions you made? 

ping @jdolence @Yurlungur

**Comment by AndrewGaspar** [comment]
Does #214 provide the necessary functionality for this?

**Comment by pgrete** [comment]
I think this should work. Let's link the issue and we'll reevaluate once #214 is in/we had time to test it downstream.
