### ISSUE TITLE
Real time commnication/chat

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#79]
During last week's call we briefly touched the idea of having an additional real time communication channel next to the bi-weekly calls.
As of now I started hanging out in the Parthenon General room on the matrix.org network: [#parthenon-general:matrix.org](https://matrix.to/#/!GXqMswuhdDaMueAtLj:matrix.org?via=matrix.org)

You don't need a desktop app and can just use the `riot.im` client in a browser (which also allows you to create an account): [click to sign up and join the room](https://riot.im/app/#/room/!GXqMswuhdDaMueAtLj:matrix.org)

By no means should this be a fixed decision and I'd be happy to discuss alternative approaches.
My main motivation to pick matrix.org over Slack, Mattermost, etc. is that it's an open, federated network that doesn't have a limit on the messages retained in the history (e.g, 10,000 for Slack which in other communities I'm member of quickly became a problem).

**Comment by jlippuner** [comment]
Great idea!

**Comment by AndrewGaspar** [comment]
Yes, I'm joining - forgot to yesterday.
