### ISSUE TITLE
ability to disable exceptions

### ISSUE THREAD

**Issue by Yurlungur** [lanl/parthenon#81]
While experimenting with performance and vectorization in #65, I discovered that many loops aren't getting vectorized because of exception handling. If I try to disable exception handling, the compiler yells at me. We need a way to disable all exception handling in the code. `trhow`, `try`, and `catch` need to be disableable globally.

**Comment by dholladay00** [comment]
This sounds fairly heavy, I've been curious about replacing the `nothrow` stuff in the ndarray accessors with `noexcept`. Could you see how that affects vectorization?

**Comment by Yurlungur** [comment]
> This sounds fairly heavy, I've been curious about replacing the `nothrow` stuff in the ndarray accessors with `noexcept`. Could you see how that affects vectorization?

Thanks, @dholladay00 that does help. I'm still seeing some failed vectorizations inside `Kokkos` internals, though. And we can't really fix that unless we disable exception handling at the compiler level.

**Comment by Yurlungur** [comment]
That said, it looks like the loops we actually care about are vectorized. So maybe it's not worth investigating further.

**Comment by AndrewGaspar** [comment]
I believe Athena did, at the very least, have the ability to disable them, so it might be worth having the option, even if it's not he default.

**Comment by pgrete** [comment]
Maybe @jmstone can share their Athena++ experience here with regard to this topic.
IIRC exception were enabled in the "outer" parts of the main loop and output handling, but vectorization of the physics kernels were not affected by that.

**Comment by jmstone** [comment]
In Athena++ we only implemented exception handling in the initialization and I/O routines, precisely because it interfered with performance.  Moreover, you don't want to keep checking for exceptions every time the main integration loop is executed.  If the code makes it through the loop once, it likely will work for the rest of the iterations (although this is not guaranteed), and so it seems a waste to check for exceptions inside the main loop.  I would be very happy to stick to this strategy since it works well in Athena++.

What would be useful in the main loop would be a "debug mode" that will stop execution when a NaN occurs, and save the state so a debugger can be used.  This was not implemented in Athena++ but would be very useful.

**Comment by AndrewGaspar** [comment]
@Yurlungur - have those exceptions been replaced by asserts?

**Comment by Yurlungur** [comment]
@AndrewGaspar I think this has been cleaned up sufficiently. Exceptions are still availabe for non performance-critical code segments and the performance critical ones have been fixed thanks to #118 by @brryan

**Comment by JoshuaSBrown** [comment]
bvals_refine.cpp
292:  throw std::runtime_error(std::string(__func__) + " is not implemented");

Checking folder cc

Checking folder fc

flux_correction_fc.cpp
47:  throw std::runtime_error(
56:  throw std::runtime_error(

config.hpp.in
54:// try/throw/catch C++ exception handling (ENABLE_EXCEPTIONS or DISABLE_EXCEPTIONS)

Checking folder coordinates

Checking folder driver

multistage.cpp
47:    throw std::invalid_argument("Invalid selection for the time integrator: " +

Checking folder interface

container_collection.cpp
28:      throw std::runtime_error("Error attempting to add a Container to a Collection");
49:      throw std::runtime_error("Non-oneCopy face variables are not yet supported");

container_collection.hpp
38:      throw std::runtime_error("Container " + label + " does not exist in collection.");

container.cpp
448:  throw std::runtime_error("Container<T>::Remove not yet implemented");

container.hpp
149:      throw std::invalid_argument(std::string("\n") + std::string(label) +
172:      throw std::invalid_argument("sparseMap_ does not have " + label);
201:      throw std::invalid_argument(std::string("\n") + std::string(label) +
214:  /// @return the CellVariable<T> if found or throw exception
220:    throw std::invalid_argument(std::string("\n") + std::string(label) +
256:  /// Remove a variable from the container or throw exception if not

metadata.cpp
50:      throw std::runtime_error(ss.str());

metadata.hpp
309:      throw std::invalid_argument("Multiple topologies sent to SetMultiple()");

sparse_variable.cpp
27:      throw std::invalid_argument("Duplicate index in create SparseVariable");
38:    throw std::invalid_argument("unsupported type in SparseVariable");

sparse_variable.hpp
111:      throw std::invalid_argument("index " + std::to_string(index) +

state_descriptor.hpp
36:  // copy constructor throw error
78:          throw std::invalid_argument(
83:          throw std::invalid_argument("Field " + field_name +

kokkos_abstraction.hpp
300:  // TODO(pgrete) if exec space is Cuda,throw error
416:  // TODO(pgrete) if exec space is Cuda,throw error

Checking folder mesh

amr_loadbalance.cpp
638:  // they could be reused, but for the moment, just throw them away for simplicity

meshblock.cpp
229:  throw std::runtime_error("MeshBlock::GetBlockSizeInBytes not yet implemented.");

mesh.cpp
1005:  throw std::runtime_error("Mesh::EnrollUserBoundaryFunction is not implemented");

Checking folder outputs

formatted_table.cpp
43:  throw std::runtime_error(std::string(__func__) + " is not implemented");

history.cpp
50:  throw std::runtime_error(std::string(__func__) + " is not implemented");

outputs.cpp
353:  throw std::runtime_error(std::string(__func__) + " is not implemented");

restart.cpp
43:  throw std::runtime_error(std::string(__func__) + " is not implemented");

vtk.cpp
234:  throw std::runtime_error(std::string(__func__) + " is not implemented");

parameter_input.cpp
326:      throw std::runtime_error("ERROR: Non-comment characters are not permitted to the "
932:    throw std::runtime_error(ss.str());

Checking folder parthenon

parthenon_arrays.hpp
104:  __attribute__((nothrow)) ParArrayNDGeneric(const ParArrayNDGeneric<Data> &t) = default;
105:  __attribute__((nothrow)) ~ParArrayNDGeneric() = default;
106:  __attribute__((nothrow)) ParArrayNDGeneric<Data> &
108:  __attribute__((nothrow)) ParArrayNDGeneric(ParArrayNDGeneric<Data> &&t) = default;
109:  __attribute__((nothrow)) ParArrayNDGeneric<Data> &
333:  __attribute__((nothrow)) ~FaceArray() = default;
383:  __attribute__((nothrow)) ~EdgeArray() = default;

Checking folder pgen

Checking folder reconstruct

characteristic.cpp
43:  throw std::runtime_error(std::string(__func__) + " is not implemented");
66:  throw std::runtime_error(std::string(__func__) + " is not implemented");

Checking folder refinement

amr_criteria.cpp
30:  throw std::invalid_argument("\n  Invalid selection for refinment method in " +

Checking folder tasks

task_id.cpp
34:  if (id < 0) throw std::invalid_argument("TaskID requires integer arguments >= 0");

**Comment by pgrete** [comment]
Are we concerned about the throws in Container and Variable classes?

**Comment by Yurlungur** [comment]
@pgrete we should replace them with `PARTHENON_THROWS` or `PARTHENON_FAIL`, depending on whether they live on the GPU.
