### ISSUE TITLE
Metadata::IsSet bug

### ISSUE THREAD

**Issue by jdolence** [lanl/parthenon#84]
The Metadata::IsSet member function checks the value of bits beyond the size of the bits_ vector, producing undefined behavior.

This version should work as expected, but it needs to be put in and a test added.

```c++
  bool IsSet(const MetadataFlag bit) const { 
    if (bit.flag_ >= bits_.size()) {
      return false;
    }
    return bits_[bit.flag_];
  }
```

**Comment by AndrewGaspar** [comment]
Oof, i should have written a better test!
