### ISSUE TITLE
Regression Tests

### ISSUE THREAD

**Issue by Yurlungur** [lanl/parthenon#89]
Bugs like #88 would be prevented if we had a suite of regression tests running along with the unit tests... I'm thinking something like `calculate_pi` or the advection test @jdolence is writing.

**Comment by Yurlungur** [comment]
In fact, I think we should just do all examples. in the `examples` directory.

**Comment by Yurlungur** [comment]
@JoshuaSBrown if I recall, you're already working on something like this, which is why I assigned you. If you end up not working on it, feel free to remove yourself.

**Comment by jdolence** [comment]
I'd say this should be a high priority.
:+1: :+1:

**Comment by pgrete** [comment]
I'm also in favor of making this a high priority and think making regression test based on all the existing examples is a good idea.

**Comment by AndrewGaspar** [comment]
Take a look at [`tst/regression`](https://github.com/PrincetonUniversity/athena-public-version/tree/master/tst/regression).

**Comment by pgrete** [comment]
I think it'd make sense to combine the python approach with the ctest base, i.e., let ctest handling all the configuration magic and use python to process the test results.
I could give a quick shot for a basic interface as I'm familiar with the python test suite in Athena++

**Comment by JoshuaSBrown** [comment]
[pi-calculator](https://github.com/lanl/parthenon/pull/165)
[advection](https://github.com/lanl/parthenon/pull/124)

**Comment by Yurlungur** [comment]
Should we close this issue? Or wait until #165 is merged in?

**Comment by JoshuaSBrown** [comment]
If we link it to #165 it will close automatically when it gets merged.
