### ISSUE TITLE
`better_athdf` missing

### ISSUE THREAD

**Issue by jlippuner** [lanl/parthenon#92]
The `athdfExample.py` script contains a reference to `better_athdf`:

```[python]
from better_athdf import better_athdf as bhdf
```
But there is no `better_athdf` module in the public Parthenon repo. Should we remove `athdfExample.py` or should we add `better_athdf` (without the better* name) to Parthenon?

**Comment by pgrete** [comment]
In what ways it better_athdf "better"? ;)
Generally, I wouldn't mind getting "better" parts upstream.

**Comment by Yurlungur** [comment]
Let's pull `better_athdf` upstream, but make it "worse."

**Comment by jdolence** [comment]
I'm doing this in #103.
